# Generated by Django 5.1.6 on 2025-03-05 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_rename_movie_moviedb_rename_seat_seatdb_and_more'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingDb',
        ),
    ]
