# Generated by Django 5.1.6 on 2025-03-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieDb',
        ),
        migrations.RenameModel(
            old_name='Seat',
            new_name='SeatDb',
        ),
        migrations.RenameModel(
            old_name='Show',
            new_name='ShowDb',
        ),
    ]
