# Generated by Django 5.1.6 on 2025-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_rename_movie_moviedb_rename_seat_seatdb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdb',
            name='total_seats',
        ),
        migrations.AlterField(
            model_name='seatdb',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seatdb',
            unique_together={('show', 'seat_number')},
        ),
    ]
