# Generated by Django 5.1.6 on 2025-03-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_rename_movie_moviedb_rename_seat_seatdb_and_more'),
        ('userApp', '0003_alter_bookingdb_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.seatdb'),
        ),
    ]
