# Generated by Django 5.1.6 on 2025-03-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_remove_showdb_total_seats_alter_seatdb_seat_number_and_more'),
        ('userApp', '0004_alter_bookingdb_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminApp.seatdb'),
        ),
    ]
